{
 "title": "GPFS Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "gpfs_fs", "label": "GPFS  Filesystem", "query": "tiger2.gpfs" },
   { "name": "cluster", "label": "Cluster", "query": "tiger" }
  ]
 },
 "panels": [
  {
   "title": "Pool Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Utilization on $gpfs_fs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gpfs_pool_data_size_bytes{fs=~\".*$gpfs_fs\"}",
     "legendFormat": "Data size {{pool_name}} (type {{pool_type}})"
    },
    {
     "expr": "gpfs_pool_data_free_bytes{fs=~\".*$gpfs_fs\"}  ",
     "legendFormat": "Data free {{pool_name}} (type {{pool_type}})"
    },
    {
     "expr": "gpfs_pool_meta_size_bytes{fs=~\".*$gpfs_fs\"}",
     "legendFormat": "Meta size {{pool_name}} (type {{pool_type}})"
    },
    {
     "expr": "gpfs_pool_meta_free_bytes{fs=~\".*$gpfs_fs\"}  ",
     "legendFormat": "Meta free {{pool_name}} (type {{pool_type}})"
    }
   ]
  },
  {
   "title": "Fileset Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "gpfs_quota_block_usage_bytes{fs=~\".*$gpfs_fs\", quota_type='FILESET'}",
     "legendFormat": "{{filesetname}}"
    }
   ]
  },
  {
   "title": "GPFS Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPFS Write BW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_bytes_write{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Read BW",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_bytes_read{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Write Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_write{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Read Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_read{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Inode Updates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_inode_updates{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS ReadDir Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_readdir{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Close Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_close{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  },
  {
   "title": "GPFS Open Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gpfs_requests_open{fs=~\".*$gpfs_fs\",host=~\"$cluster.*\"}[1m])",
     "legendFormat": "{{host}} on {{fs}}"
    }
   ]
  }
 ]
}